[package]
name = "mersenne-primes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
rayon = "1.5"
clap = { version = "3.1", features = ["derive"] }
